name: Docker

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 0'
  push:
    # Publish `master` as Docker `latest` image.
    branches: master

jobs:
  main:
    name: Build IAC Builder Container
    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
          name: Login to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx 1
        uses: docker/setup-buildx-action@v2
        id: builder1
      -
        name: Build and push Latest
        id: docker_build1
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder1.outputs.name }}
          push: true
          build-args: |
            HELM_VERSION=3.13.3
          tags: |
            bowens/docker-iac-builder:latest
            ghcr.io/taz77/docker-iac-builder:latest

      -
        name: Notify Slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
          channel-id: 'dev'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        if: always() # Pick up events even if the job fails or is canceled.
