name: Docker

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 0'
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

jobs:
  main:
    name: Build IAC Builder Container
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -   name: Login to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: |
            name=ghcr.io/taz77/docker-iac-builder
            name=bowens/docker-iac-builder
          tags: |
            type=schedule
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr

      - name: Set up Docker Buildx 1
        uses: docker/setup-buildx-action@v3
        id: builder1
      - name: Build and push Latest
        id: docker_build1
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.builder1.outputs.name }}
          platforms: linux/amd64,linux/arm/v7
          push: true
          build-args: |
            HELM_VERSION=3.16.2
          tags: ${{ steps.docker_meta.outputs.tags }}

      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
          channel-id: 'dev'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        if: always() # Pick up events even if the job fails or is canceled.
